data-set
Autonomobile/AutoPylot pull request #52
Opened 2022-03-05 23:25 UTC by DieuCrevette

NOT FINISHED DO **NOT CLOSE** @Maximellerbach

2022-03-06 12:56 UTC, DieuCrevette commented
two erros on the test functions :

- [ ] Assert error on the test_load_data_set_generator
- [ ] Couldn't convert test___get_time_stamp (idk why need of investigation)

2022-03-07 19:03 UTC, Maximellerbach approved these changes
lgtm

2022-03-07 19:05 UTC, Maximellerbach requested changes

2022-03-07 19:05 UTC, Maximellerbach commented on autopylot/datasets/dataset.py
> +    return load_multiple_dataset(__sort_paths(dirpath))
wait wait wait, this is not coherent, what are we sorting ?

2022-03-07 19:07 UTC, Maximellerbach commented on autopylot/datasets/dataset.py
> +def load_multiple_data_set_generator(dirpath, flat=False):
typo here

2022-03-08 12:17 UTC, Maximellerbach commented
The tests are not passing because of the fact that linux is not behaving in the same way regarding the file order, let's see this afternoon what we can do to solve this.
my guess would be to add a mark for the functions only working on windows, and disable them in the github action.

2022-03-08 19:40 UTC, Maximellerbach approved these changes
Good for merging !

2022-03-08 20:00 UTC, merged